# Generated by Django 4.1.6 on 2023-02-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
