# Generated by Django 4.1.6 on 2023-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='students/', verbose_name='Фото профиля'),
        ),
    ]
