# Generated by Django 3.2.16 on 2023-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_plan_alter_month_title_result_plan_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
