# Generated by Django 4.1.6 on 2023-02-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='begin',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='end',
            field=models.DateField(verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.plan', verbose_name='План'),
        ),
    ]
