# Generated by Django 4.1.6 on 2023-02-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_event_level_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.plan', verbose_name='План'),
        ),
    ]
