# Generated by Django 4.1.6 on 2023-02-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_shedule_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.shedule', verbose_name='Расписание')),
            ],
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/%d/', verbose_name='Изображение')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.report', verbose_name='Отчет')),
            ],
        ),
    ]
