# Generated by Django 4.1.6 on 2023-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_report_reportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Отчет о работе', max_length=60, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
