# Generated by Django 4.1.6 on 2023-02-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_report_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportimage',
            old_name='image',
            new_name='url',
        ),
    ]
