# Generated by Django 4.1.6 on 2023-02-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_rename_image_reportimage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportimage',
            old_name='url',
            new_name='image',
        ),
    ]
