# Generated by Django 4.1.6 on 2023-02-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0017_alter_report_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Баллы')),
                ('event_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventlevel', verbose_name='Уровень')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.nomination', verbose_name='Номинация')),
            ],
        ),
    ]
