# Generated by Django 4.1.6 on 2023-02-12 14:43

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_documenttype_eventrole_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.models.get_user_path)),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.achievement', verbose_name='Достижение')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.activity', verbose_name='Участие')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.documenttype', verbose_name='Тип документа')),
            ],
        ),
    ]
