# Generated by Django 4.1.6 on 2023-02-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.activity', verbose_name='Участие'),
        ),
    ]
